insert into question (id,ques,option1,option2,option3,option4,att) values (1,'Who is the Prime Minister of India?','Narendra Modi','Pinarayi Vijayan','Mamatha banerjee','Arvind Kejriwal','');
insert into question (id,ques,option1,option2,option3,option4,att) values (2,'Which city is the capital of India?','Mumbai','New Delhi','Chennai','Kolkata','');
insert into question (id,ques,option1,option2,option3,option4,att) values (3,'Who is the Chief Minister of Uttar Pradesh?','Stallin','Pinarayi Vijayan','Yogi Adityanath','Arvind Kejriwal','');
insert into question (id,ques,option1,option2,option3,option4,att) values (4,'Which city is the Financial capital of India?','Mumbai','New Delhi','Chennai','Kolkata','');
insert into question (id,ques,option1,option2,option3,option4,att) values (5,'Which city is te capital of Karnataka?','Mumbai','New Delhi','Chennai','Bangaluru','');
insert into question (id,ques,option1,option2,option3,option4,att) values (6,'Who is the Chief Minister of Kerala?','Narendra Modi','Pinarayi Vijayan','Mamatha banerjee','Arvind Kejriwal','');
insert into question (id,ques,option1,option2,option3,option4,att) values (7,'Who is the Chief Minister of Tamil Nadu?','Narendra Modi','Pinarayi Vijayan','Mamatha banerjee','Stallin','');
insert into answer (id,ans) values (1,'Narendra Modi');
insert into answer (id,ans) values (2,'New Delhi');
insert into answer (id,ans) values (3,'Yogi Adithyanath');
insert into answer (id,ans) values (4,'Mumbai');
insert into answer (id,ans) values (5,'Bangaluru');
insert into answer (id,ans) values (6,'Pinarayi Vijayan');
insert into answer (id,ans) values (7,'Stallin');
insert into answerkey (id,a_key) values(1,'a');
insert into answerkey (id,a_key) values(2,'b');
insert into answerkey (id,a_key) values(3,'c');
insert into answerkey (id,a_key) values(4,'a');
insert into answerkey (id,a_key) values(5,'d');
insert into answerkey (id,a_key) values(6,'b');
insert into answerkey (id,a_key) values(7,'d');